package dev.yaul.twocha.security

import android.content.Context
import android.content.SharedPreferences
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import uniffi.twocha_mobile.generateKeypair
import uniffi.twocha_mobile.publicKeyFor

/**
 * Stores the device's X25519 client identity.
 *
 * The private key is generated by the native engine ([generateKeypair]) and kept
 * in [EncryptedSharedPreferences] (a master key in the Android Keystore encrypts
 * the value at rest). It is never exported; only the base64 public key is shown
 * to the user to register in the server's peer list. The private key is handed to
 * the engine at connect time via `TwochaTunnel.start(..., privateKeyB64, ...)`.
 */
class KeyManager(context: Context) {

    private val prefs: SharedPreferences by lazy {
        val masterKey = MasterKey.Builder(context.applicationContext)
            .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
            .build()
        EncryptedSharedPreferences.create(
            context.applicationContext,
            PREFS_NAME,
            masterKey,
            EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
            EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
        )
    }

    /** True if an identity has already been generated. */
    fun hasIdentity(): Boolean = prefs.contains(KEY_PRIVATE)

    /** The stored base64 private key, generating a new identity on first use. */
    fun privateKeyB64(): String =
        prefs.getString(KEY_PRIVATE, null) ?: generateAndStore().privateKeyB64

    /** The base64 public key for the stored identity, generating one if absent. */
    fun publicKeyB64(): String {
        val priv = prefs.getString(KEY_PRIVATE, null) ?: return generateAndStore().publicKeyB64
        return publicKeyFor(priv)
    }

    /** Discard the current identity and generate a fresh one. */
    fun regenerate(): String = generateAndStore().publicKeyB64

    private fun generateAndStore(): StoredKey {
        val kp = generateKeypair()
        prefs.edit().putString(KEY_PRIVATE, kp.privateKeyB64).apply()
        return StoredKey(kp.privateKeyB64, kp.publicKeyB64)
    }

    private data class StoredKey(val privateKeyB64: String, val publicKeyB64: String)

    companion object {
        private const val PREFS_NAME = "twocha_identity"
        private const val KEY_PRIVATE = "client_private_key_b64"
    }
}
